### ISSUE TITLE
elixir logo

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwl-website#101]
Has black background on main page.

![Screenshot_20220303-113934](https://user-images.githubusercontent.com/1330696/156548551-f7e7affe-fa85-4802-a4d8-dd514d44b9b4.png)

Missing elements in the gallery Page 
![Screenshot_20220303-114043](https://user-images.githubusercontent.com/1330696/156548785-3b0b8668-fadc-4eff-bfed-589bc4e50da0.png)

@stain suggest using https://www.dropbox.com/s/1visx657xh1pmms/ELIXIR_logo_white_background.svg?dl=0

**Comment by mr-c** [comment]
Oh, a PR to the main branch is the normal method. I don't know about that branch.

**Comment by lunacodes** [comment]
@stain `add-jekyll-site` branch was from when we re-coded the old site into Jekyll. It shouldn't be used at this point. Sorry any confusion.

`staging` was being used for the deploy preview at the time, which output to https://www.commonwl.org/cwl-staging/ (Note: it's not working with the new site yet). Since netlify auto-generates the deploy previews, I'm not sure that we still need it. 

@mr-c let me know if you want to keep the `staging` branch or not, and I'll update the EDITING and README docs to reflect the process.

**Comment by mr-c** [comment]
Yeah, I don't think we need the staging branch anymore.  Thanks for the explanation!

**Comment by swzCuroverse** [comment]
@lunacodes might want to comment on this.  I think in general a staging branch is nice to double check everything looks good before you push to the live site.  I wouldn't change it until Luna can verify that is the proper process?

**Comment by swzCuroverse** [comment]
I think the staging is nice for people to check that it appears as they would think before pushing to the main site. But that is just my inclination.
