### ISSUE TITLE
SEO for website?

### ISSUE THREAD

**Issue by swzCuroverse** [common-workflow-language/cwl-website#114]
@lunacodes looks like when I google cwl, cwl workflow or common workflow language - we don't really get hits on the main website - we get mostly links to the standards or the user guide.  The standards have a link back to the main page but the user guide doesn't.  Any ideas on how to make the website show up better in google searches?  Thanks!  Also is it possible to make a link back to the main page from the User Guide @tetron ?

**Comment by lunacodes** [comment]
@swzCuroverse thanks for bringing this up. The live site's improperly generating the `<meta name="robots" content="noindex" />`. I just pushed a fix for it. Whoever has access to the site in [Google Search Console](https://search.google.com/search-console/) should tell google to re-crawl the page now. (otherwise, Google does it periodically - but no idea when that will be).

> The standards have a link back to the main page but the user guide doesn't

I could add that. Would it make sense to add the logo (linking to the main site) to the top nav, before Home? Or do you want it somewhere else

![User_Guide_With_CWL_Nav_Logo](https://user-images.githubusercontent.com/10420402/159188033-0249cf40-57fe-4946-bdab-298d8c746944.png)

**Comment by mr-c** [comment]
I merged @lunacodes fix and requested a new crawl of the main page. Thanks!

**Comment by swzCuroverse** [comment]
Thank you @mr-c and @lunacodes

**Comment by swzCuroverse** [comment]
@lunacodes - it now shows up as the first hit on google!  thanks.
