### ISSUE TITLE
Mobile Usability issue: Clickable elements too close together

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwl-website#64]
https://search.google.com/search-console/mobile-usability/drilldown?resource_id=sc-domain%3Acommonwl.org&item_key=CAs&hl=en-DE&sharing_key=eB0gUJRGM5X49nZJtLxbig

Example: https://www.commonwl.org/v1.2/Workflow.html

**Comment by lunacodes** [comment]
@mr-c  This is most likely being caused by the body's `font-size: 14px`. On the main site, we fixed it by upping it to `font-size: 0.9375rem` (15px). It's possible the table `line-height: 1.42857143` (example: [4. Workflow -> Extensions ->](https://www.commonwl.org/v1.2/Workflow.html#Extensions) table. On the main site, we have it at `line-height: 1.43`, but I think it needs to be at least 1.5 (I'd recommend 1.625), given the `requirements` section of that table. 

Let me know if you want me to add a stylesheet with this in it.

**Comment by mr-c** [comment]
> Let me know if you want me to add a stylesheet with this in it.

Yes, please!
