### ISSUE TITLE
Minor edits on the new draft of the website

### ISSUE THREAD

**Issue by swzCuroverse** [common-workflow-language/cwl-website#94]
These are minor edits - and do not need to prevent the website from going live, but I just wanted to list them here for @lunacodes.
* For the development tools page: 
** you probably don't need the extra development tools header. https://deploy-preview-75--cwl-website.netlify.app/tools/ 
** capitalize every description in the unless it is lowercase because of the tool name, e.g. cwltool
* For the implementations page:
**  Local is sometimes capitalized and sometimes not -- I would personally suggest lowercase
* For the repos page:
**  Remove any periods after entries so they are all consistent.
* For the projects page:
** Capitalize all entries and remove periods
* For the gallery page:
** Some of the entries are missing periods at the end.

Most of these were my fault , but if you could help clean them up - that would really be helpful.

These are more suggestions than minor edits to consider:
* Center the logos on the bottom row in the minor users gallery on the main page -- they look a little odd to me justified to the left.  No sure if that is just me though.

**Comment by lunacodes** [comment]
@swzCuroverse just finished up the revisions here.

In `tools.md`: Can I add the following description for CWL for Go: "A parser of [CWL](https://github.com/common-workflow-language/common-workflow-language) file and input files based on CWL" (also should it be CWL file or files)

Re: the Mini Gallery - I think it looks ok as is, and would prefer not to center them, since the logos won't line up properly if there's ever an odd number. (it's also a bit tricky to code, with the current structure)

**Comment by lunacodes** [comment]
@swzCuroverse just wanna check if you saw my comment here.

**Comment by mr-c** [comment]
> @lunacodes no, I didn't sorry about that. OK - with not centering. They describe it as : "CWL (and input file) parser for Golang" so is that OK - or would you prefere "A CWL (and input file) parser for Golang" or "A parser of CWL and input files for Golang"?

FYI, I already fixed the description of "CWL for Go" in https://github.com/common-workflow-language/cwl-website/commit/232cd0122ef828e70a424fb8e033d22206d52ca1
